sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 114514
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: sky-take-out-banyue

  wechat:
    appid: wx491fd2145b42e2c6
    secret: ${WECHAT_SECRET}
